package org.obi.attr.javac

/**
 * The debugging information added to the generated bytecode.
 */
sealed trait DebugInformation {
    def option: String
}

/**
 * No debugging information will be added to the generated bytecode.
 */
final case object None extends DebugInformation {
    override def option = "none"
}

/**
 * Source file debugging information will be added to the bytecode.
 */
final case object Source extends DebugInformation {
    override def option = "source"
}

/**
 * Line number debugging information will be added to the bytecode.
 */
final case object Lines extends DebugInformation {
    override def option = "lines"
}

/**
 * Local variable debugging information will be added to the bytecode.
 */
final case object Vars extends DebugInformation {
    override def option = "vars"
}

/**
 * All debugging information (source, lines, vars) will be added to the bytecode.
 */
final case object All extends DebugInformation {
    lazy val types = List(Source, Lines, Vars)

    override def option = types.map(_.option).mkString(",")
}
